// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(InformationSystemDbContext))]
    [Migration("20250328093832_fixconnections")]
    partial class fixconnections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BalanceAnalysis", b =>
                {
                    b.Property<DateTime>("Period")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BalanceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ProfitOrLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TradePointId")
                        .HasColumnType("uuid");

                    b.HasKey("Period");

                    b.ToTable("BalanceAnalysis");
                });

            modelBuilder.Entity("DebtPayable", b =>
                {
                    b.Property<Guid>("DebtPayableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreditorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid");

                    b.HasKey("DebtPayableId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("DebtPayables");
                });

            modelBuilder.Entity("DebtReceivable", b =>
                {
                    b.Property<Guid>("DebtReceivableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IncomeId")
                        .HasColumnType("uuid");

                    b.HasKey("DebtReceivableId");

                    b.HasIndex("IncomeId");

                    b.ToTable("DebtReceivables");
                });

            modelBuilder.Entity("Domain.Models.Incident", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IncidentDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IncidentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IncidentId");

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("Expense", b =>
                {
                    b.Property<Guid>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BalanceAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BalanceAnalysisPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SalaryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TradePointEconomicsId")
                        .HasColumnType("uuid");

                    b.HasKey("ExpenseId");

                    b.HasIndex("BalanceAnalysisPeriod");

                    b.HasIndex("SalaryId");

                    b.HasIndex("TradePointEconomicsId");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("FinishedGoodsWarehouse", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IncomeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PotentialRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("IncomeId");

                    b.ToTable("FinishedGoodsWarehouse");
                });

            modelBuilder.Entity("Income", b =>
                {
                    b.Property<Guid>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BalanceAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BalanceAnalysisPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TradePointEconomicsId")
                        .HasColumnType("uuid");

                    b.HasKey("IncomeId");

                    b.HasIndex("BalanceAnalysisPeriod");

                    b.HasIndex("TradePointEconomicsId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("Log", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("RawMaterialWarehouse", b =>
                {
                    b.Property<Guid>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PurchaseCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("MaterialId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("RawMaterialWarehouse");
                });

            modelBuilder.Entity("Salary", b =>
                {
                    b.Property<Guid>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("SalaryId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("TradePoint", b =>
                {
                    b.Property<Guid>("TradePointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TradePointId");

                    b.ToTable("TradePoints", (string)null);
                });

            modelBuilder.Entity("TradePointEconomics", b =>
                {
                    b.Property<Guid>("TradePointEconomicsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Expenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Period")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TradePointId")
                        .HasColumnType("uuid");

                    b.HasKey("TradePointEconomicsId");

                    b.HasIndex("TradePointId");

                    b.ToTable("TradePointEconomics");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Worker", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("WorkerId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("DebtPayable", b =>
                {
                    b.HasOne("Expense", "Expense")
                        .WithMany("DebtPayables")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("DebtReceivable", b =>
                {
                    b.HasOne("Income", "Income")
                        .WithMany("DebtReceivables")
                        .HasForeignKey("IncomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Income");
                });

            modelBuilder.Entity("Expense", b =>
                {
                    b.HasOne("BalanceAnalysis", "BalanceAnalysis")
                        .WithMany("Expenses")
                        .HasForeignKey("BalanceAnalysisPeriod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salary", "Salary")
                        .WithMany()
                        .HasForeignKey("SalaryId");

                    b.HasOne("TradePointEconomics", "TradePointEconomics")
                        .WithMany()
                        .HasForeignKey("TradePointEconomicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BalanceAnalysis");

                    b.Navigation("Salary");

                    b.Navigation("TradePointEconomics");
                });

            modelBuilder.Entity("FinishedGoodsWarehouse", b =>
                {
                    b.HasOne("Income", "Income")
                        .WithMany("FinishedGoodsWarehouses")
                        .HasForeignKey("IncomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Income");
                });

            modelBuilder.Entity("Income", b =>
                {
                    b.HasOne("BalanceAnalysis", "BalanceAnalysis")
                        .WithMany("Incomes")
                        .HasForeignKey("BalanceAnalysisPeriod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradePointEconomics", "TradePointEconomics")
                        .WithMany()
                        .HasForeignKey("TradePointEconomicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BalanceAnalysis");

                    b.Navigation("TradePointEconomics");
                });

            modelBuilder.Entity("Log", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RawMaterialWarehouse", b =>
                {
                    b.HasOne("Expense", "Expense")
                        .WithMany("RawMaterialWarehouses")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("Salary", b =>
                {
                    b.HasOne("Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("TradePointEconomics", b =>
                {
                    b.HasOne("TradePoint", "TradePoint")
                        .WithMany()
                        .HasForeignKey("TradePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradePoint");
                });

            modelBuilder.Entity("BalanceAnalysis", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("Expense", b =>
                {
                    b.Navigation("DebtPayables");

                    b.Navigation("RawMaterialWarehouses");
                });

            modelBuilder.Entity("Income", b =>
                {
                    b.Navigation("DebtReceivables");

                    b.Navigation("FinishedGoodsWarehouses");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
