// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(InformationSystemDbContext))]
    [Migration("20250327100348_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.BalanceAnalysis", b =>
                {
                    b.Property<Guid>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Period")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ProfitOrLoss")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalExpense")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("TradePointId")
                        .HasColumnType("uuid");

                    b.HasKey("BalanceId");

                    b.HasIndex("TradePointId");

                    b.ToTable("BalanceAnalysis");
                });

            modelBuilder.Entity("Domain.Models.DebtPayable", b =>
                {
                    b.Property<Guid>("DebtPayableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CreditorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid");

                    b.HasKey("DebtPayableId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("DebtsPayable", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DebtReceivable", b =>
                {
                    b.Property<Guid>("DebtReceivableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IncomeId")
                        .HasColumnType("uuid");

                    b.HasKey("DebtReceivableId");

                    b.HasIndex("IncomeId");

                    b.ToTable("DebtReceivable");
                });

            modelBuilder.Entity("Domain.Models.Expense", b =>
                {
                    b.Property<Guid>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BalanceAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SalaryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TradePointEconomicsId")
                        .HasColumnType("uuid");

                    b.HasKey("ExpenseId");

                    b.HasIndex("BalanceAnalysisId");

                    b.HasIndex("SalaryId");

                    b.HasIndex("TradePointEconomicsId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Domain.Models.FinishedGoodsWarehouse", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IncomeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PotentialRevenue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("IncomeId");

                    b.ToTable("FinishedGoodsWarehouse");
                });

            modelBuilder.Entity("Domain.Models.Incident", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IncidentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IncidentId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("Domain.Models.Income", b =>
                {
                    b.Property<Guid>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BalanceAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TradePointEconomicsId")
                        .HasColumnType("uuid");

                    b.HasKey("IncomeId");

                    b.HasIndex("BalanceAnalysisId");

                    b.HasIndex("TradePointEconomicsId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("Domain.Models.Log", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uuid");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Domain.Models.RawMaterialWarehouse", b =>
                {
                    b.Property<Guid>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("PurchaseCost")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("MaterialId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("RawMaterialWarehouse");
                });

            modelBuilder.Entity("Domain.Models.Salary", b =>
                {
                    b.Property<Guid>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("SalaryId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("Domain.Models.TradePoint", b =>
                {
                    b.Property<Guid>("TradePointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("TradePointId");

                    b.ToTable("TradePoints");
                });

            modelBuilder.Entity("Domain.Models.TradePointEconomics", b =>
                {
                    b.Property<Guid>("TradePointEconomicsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Expenses")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Period")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Profit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TradePointId")
                        .HasColumnType("uuid");

                    b.HasKey("TradePointEconomicsId");

                    b.HasIndex("TradePointId")
                        .IsUnique();

                    b.ToTable("TradePointEconomics");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.Worker", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("WorkerId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("Domain.Models.BalanceAnalysis", b =>
                {
                    b.HasOne("Domain.Models.TradePoint", "TradePoint")
                        .WithMany()
                        .HasForeignKey("TradePointId");

                    b.Navigation("TradePoint");
                });

            modelBuilder.Entity("Domain.Models.DebtPayable", b =>
                {
                    b.HasOne("Domain.Models.Expense", "Expense")
                        .WithMany("DebtsPayable")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("Domain.Models.DebtReceivable", b =>
                {
                    b.HasOne("Domain.Models.Income", "Income")
                        .WithMany("DebtsReceivable")
                        .HasForeignKey("IncomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Income");
                });

            modelBuilder.Entity("Domain.Models.Expense", b =>
                {
                    b.HasOne("Domain.Models.BalanceAnalysis", "BalanceAnalysis")
                        .WithMany("Expenses")
                        .HasForeignKey("BalanceAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Salary", "Salary")
                        .WithMany("Expenses")
                        .HasForeignKey("SalaryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.TradePointEconomics", "TradePointEconomics")
                        .WithMany()
                        .HasForeignKey("TradePointEconomicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BalanceAnalysis");

                    b.Navigation("Salary");

                    b.Navigation("TradePointEconomics");
                });

            modelBuilder.Entity("Domain.Models.FinishedGoodsWarehouse", b =>
                {
                    b.HasOne("Domain.Models.Income", "Income")
                        .WithMany("FinishedGoodsWarehouses")
                        .HasForeignKey("IncomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Income");
                });

            modelBuilder.Entity("Domain.Models.Income", b =>
                {
                    b.HasOne("Domain.Models.BalanceAnalysis", "BalanceAnalysis")
                        .WithMany("Incomes")
                        .HasForeignKey("BalanceAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.TradePointEconomics", "TradePointEconomics")
                        .WithMany()
                        .HasForeignKey("TradePointEconomicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BalanceAnalysis");

                    b.Navigation("TradePointEconomics");
                });

            modelBuilder.Entity("Domain.Models.Log", b =>
                {
                    b.HasOne("Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.RawMaterialWarehouse", b =>
                {
                    b.HasOne("Domain.Models.Expense", "Expense")
                        .WithMany("RawMaterialWarehouses")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("Domain.Models.Salary", b =>
                {
                    b.HasOne("Domain.Models.Worker", "Worker")
                        .WithMany("Salaries")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Domain.Models.TradePointEconomics", b =>
                {
                    b.HasOne("Domain.Models.TradePoint", "TradePoint")
                        .WithOne("TradePointEconomics")
                        .HasForeignKey("Domain.Models.TradePointEconomics", "TradePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradePoint");
                });

            modelBuilder.Entity("Domain.Models.BalanceAnalysis", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("Domain.Models.Expense", b =>
                {
                    b.Navigation("DebtsPayable");

                    b.Navigation("RawMaterialWarehouses");
                });

            modelBuilder.Entity("Domain.Models.Income", b =>
                {
                    b.Navigation("DebtsReceivable");

                    b.Navigation("FinishedGoodsWarehouses");
                });

            modelBuilder.Entity("Domain.Models.Salary", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("Domain.Models.TradePoint", b =>
                {
                    b.Navigation("TradePointEconomics")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Worker", b =>
                {
                    b.Navigation("Salaries");
                });
#pragma warning restore 612, 618
        }
    }
}
